import type { AdminLang } from "./admin-lang";

/**
 * Человеческие подписи к полям.
 *
 * В JSON поле зовётся `benefits.items.4.title`, и по такому имени невозможно
 * понять, что правишь. Расшифровываем по последнему сегменту пути, а номер
 * элемента списка показываем отдельно: «Пункт 5 · Заголовок».
 *
 * Точечные переопределения нужны там, где общее правило врёт: например,
 * `stats.network.value` — это не «значення», а конкретная цифра сети.
 */

const leaf: Record<AdminLang, Record<string, string>> = {
  uk: {
    badge: "Плашка над заголовком",
    title: "Заголовок",
    titleStart: "Заголовок — початок",
    titleStrong: "Заголовок — виділена частина",
    titleAccent: "Заголовок — акцент",
    titleEnd: "Заголовок — кінець",
    subtitle: "Підзаголовок",
    lead: "Вступний абзац",
    text: "Текст",
    label: "Підпис",
    name: "Назва",
    role: "Посада",
    value: "Значення",
    unit: "Одиниця виміру",
    a: "Перше число",
    b: "Друге число",
    aUnit: "Одиниця першого числа",
    bUnit: "Одиниця другого числа",
    year: "Рік",
    share: "Довжина смуги, %",
    city: "Місто",
    phone: "Телефон",
    email: "Пошта",
    note: "Примітка під формою",
    contact: "Підпис над контактами",
    quote: "Цитата",
    quoteStart: "Цитата — початок",
    quoteMid: "Цитата — середина",
    quoteStrong1: "Цитата — виділення 1",
    quoteStrong2: "Цитата — виділення 2",
    p1: "Абзац 1",
    p2: "Абзац 2",
    p3: "Абзац 3",
    p1Strong: "Абзац 1 — виділення",
    p2Strong: "Абзац 2 — виділення",
    p3Strong: "Абзац 3 — виділення",
    source: "Джерела даних",
    description: "Опис",
    ogTitle: "Заголовок для соцмереж",
    ogDescription: "Опис для соцмереж",
    body: "Текст сторінки",
    accept: "Кнопка «Прийняти»",
    decline: "Кнопка «Тільки необхідні»",
    policy: "Посилання на політику",
    open: "Кнопка «Навігація»",
    close: "Кнопка «Закрити»",
    tagline: "Підпис у меню",
    more: "Кнопка «Дізнатися більше»",
    go: "Кнопка «Перейти»",
    presentation: "Кнопка «Отримати презентацію»",
    franchise: "Кнопка «Дізнатися про франшизу»",
    formats: "Кнопка «Переглянути формати»",
    tagA: "Тег 1",
    tagB: "Тег 2",
    nameLabel: "Підпис поля «Ім'я»",
    namePlaceholder: "Підказка в полі «Ім'я»",
    phoneLabel: "Підпис поля «Телефон»",
    cityLabel: "Підпис поля «Місто»",
    cityPlaceholder: "Підказка в полі «Місто»",
    countrySearch: "Підказка в пошуку країни",
    errorRequired: "Помилка: поле порожнє",
    errorPhone: "Помилка: невірний телефон",
    errorServer: "Помилка: збій відправки",
    sending: "Напис під час відправки",
    successTitle: "Дякуємо — заголовок",
    successText: "Дякуємо — текст",
    download: "Кнопка завантаження",
    home: "Кнопка «На головну»",
    youtube: "Текст біля YouTube",
    youtubeLink: "Назва каналу",
    youtubeCta: "Кнопка на відео (телефон)",
    paybackLabel: "Підпис «Термін окупності»",
    paybackValue: "Значення окупності",
    growthStart: "Зростання — початок",
    growthValue: "Зростання — число",
    growthEnd: "Зростання — кінець",
    workshops: "Кількість цехів",
    workshopsUnit: "Слово «цех»",
    points: "Кількість пунктів",
    pointsUnit: "Слово «пункт»",
    pillarsTitle: "Заголовок «Три кити»",
    pillarsTitleStrong: "Заголовок «Три кити» — виділення",
    beforeTitle: "Підпис «До відкриття»",
    afterTitle: "Підпис «Після відкриття»",
  },
  ru: {
    badge: "Плашка над заголовком",
    title: "Заголовок",
    titleStart: "Заголовок — начало",
    titleStrong: "Заголовок — выделенная часть",
    titleAccent: "Заголовок — акцент",
    titleEnd: "Заголовок — конец",
    subtitle: "Подзаголовок",
    lead: "Вступительный абзац",
    text: "Текст",
    label: "Подпись",
    name: "Название",
    role: "Должность",
    value: "Значение",
    unit: "Единица измерения",
    a: "Первое число",
    b: "Второе число",
    aUnit: "Единица первого числа",
    bUnit: "Единица второго числа",
    year: "Год",
    share: "Длина полосы, %",
    city: "Город",
    phone: "Телефон",
    email: "Почта",
    note: "Примечание под формой",
    contact: "Подпись над контактами",
    quote: "Цитата",
    quoteStart: "Цитата — начало",
    quoteMid: "Цитата — середина",
    quoteStrong1: "Цитата — выделение 1",
    quoteStrong2: "Цитата — выделение 2",
    p1: "Абзац 1",
    p2: "Абзац 2",
    p3: "Абзац 3",
    p1Strong: "Абзац 1 — выделение",
    p2Strong: "Абзац 2 — выделение",
    p3Strong: "Абзац 3 — выделение",
    source: "Источники данных",
    description: "Описание",
    ogTitle: "Заголовок для соцсетей",
    ogDescription: "Описание для соцсетей",
    body: "Текст страницы",
    accept: "Кнопка «Принять»",
    decline: "Кнопка «Только необходимые»",
    policy: "Ссылка на политику",
    open: "Кнопка «Навигация»",
    close: "Кнопка «Закрыть»",
    tagline: "Подпись в меню",
    more: "Кнопка «Узнать больше»",
    go: "Кнопка «Перейти»",
    presentation: "Кнопка «Получить презентацию»",
    franchise: "Кнопка «Узнать о франшизе»",
    formats: "Кнопка «Посмотреть форматы»",
    tagA: "Тег 1",
    tagB: "Тег 2",
    nameLabel: "Подпись поля «Имя»",
    namePlaceholder: "Подсказка в поле «Имя»",
    phoneLabel: "Подпись поля «Телефон»",
    cityLabel: "Подпись поля «Город»",
    cityPlaceholder: "Подсказка в поле «Город»",
    countrySearch: "Подсказка в поиске страны",
    errorRequired: "Ошибка: поле пустое",
    errorPhone: "Ошибка: неверный телефон",
    errorServer: "Ошибка: сбой отправки",
    sending: "Надпись во время отправки",
    successTitle: "Спасибо — заголовок",
    successText: "Спасибо — текст",
    download: "Кнопка скачивания",
    home: "Кнопка «На главную»",
    youtube: "Текст возле YouTube",
    youtubeLink: "Название канала",
    youtubeCta: "Кнопка на видео (телефон)",
    paybackLabel: "Подпись «Срок окупаемости»",
    paybackValue: "Значение окупаемости",
    growthStart: "Рост — начало",
    growthValue: "Рост — число",
    growthEnd: "Рост — конец",
    workshops: "Количество цехов",
    workshopsUnit: "Слово «цех»",
    points: "Количество пунктов",
    pointsUnit: "Слово «пункт»",
    pillarsTitle: "Заголовок «Три кита»",
    pillarsTitleStrong: "Заголовок «Три кита» — выделение",
    beforeTitle: "Подпись «До открытия»",
    afterTitle: "Подпись «После открытия»",
  },
};

/** Куда ведёт группа полей: «Пункт 5», «Крок 2», «Формат 1» */
const groupWords: Record<AdminLang, Record<string, string>> = {
  uk: {
    items: "Пункт",
    points: "Пункт",
    years: "Рік",
    figures: "Цифра",
    pillars: "Картка",
    before: "Пункт «До відкриття»",
    after: "Пункт «Після відкриття»",
    slides: "Слайд",
    links: "Посилання",
    columns: "Колонка",
  },
  ru: {
    items: "Пункт",
    points: "Пункт",
    years: "Год",
    figures: "Цифра",
    pillars: "Карточка",
    before: "Пункт «До открытия»",
    after: "Пункт «После открытия»",
    slides: "Слайд",
    links: "Ссылка",
    columns: "Колонка",
  },
};

/**
 * Подпись для пути вида `benefits.items.4.title`.
 * Возвращает «Пункт 5 · Заголовок»; если расшифровки нет — сам путь,
 * чтобы поле всё равно можно было опознать.
 */
export function fieldLabel(path: string, lang: AdminLang, leafOnly = false) {
  const parts = path.split(".");
  const last = parts.at(-1) ?? path;

  const name = leaf[lang][last];
  const index = parts.findIndex((p) => /^\d+$/.test(p));

  // внутри блока номер элемента уже написан в его заголовке
  if (leafOnly && name) return name;

  if (index > 0) {
    const group = groupWords[lang][parts[index - 1]] ?? parts[index - 1];
    const number = Number(parts[index]) + 1;
    // сам элемент списка — строка, а не объект: «Пункт 3» без уточнения
    const suffix = name && index < parts.length - 1 ? ` · ${name}` : "";
    return `${group} ${number}${suffix}`;
  }

  return name ?? path;
}
